service:
  port: 8830
  context-path: /chatterbox
# 主数据源
database:
  ip: 139.196.182.46
  port: 3306
  name: chatterbox
  username: root
  password: ll5271211314
  installation-path: /usr/local/software/mysql/mysql-8.0.29/bin/ # 数据库安装路径
  backup-path: /home/project/slipper/admin/resource/mysql # 数据库备份文件存放路径
  statViewServlet: # 监控
    url-pattern: /druid/*
    username: gumingchen
    password: gumingchen
# redis
redis:
  database: 1
  host: 139.196.182.46
  port: 6379
  password: ll5271211314
# json web token
jwt:
  secret: efe1679416b57fd5af7ee0969d79ec94bf40e0268ba423681f47e4e84bd352dc # 秘钥
  expire: 604800 # 过期是时间（秒）
# netty
netty:
  port: 8831
  url: ws://localhost:${netty.port}/${service.context-path}/websocket/{token}
# 文件配置
file:
  path: /home/project/slipper/chatterbox/resource # 存储路径
  url: http://admin.gumingchen.icu # 访问路径
# 邮箱配置
mail:
  email: gumingchen@foxmail.com # 邮箱地址
  username: gumingchen@foxmail.com # 用户名
  password: egjerfvcqakyjbgb # 密码
  protocol: smtp # 协议
  host: smtp.qq.com # 主机
  port: 465 # 端口

